# -*- coding: utf-8 -*-
"""Plots, Accuracy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13y8Lz0gpvXtl83Fqnx_QKXvKQjH0fpeD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("Eval_epoch.csv")
# Dataset a model-method-epoch-seed combination per row with the following variables:
# - Model = ["BERT", "RoBERTa", "BERTweet"]
# - Epoch = 1:30
# - Seed = 42:61
# - prec_neg (Precision of negative case, i.e., precision of those labelled 'civil'; TN/(TN+FN))
# - rec_neg (Recall of negative case, i.e., recall of ground-truth 'civil'; TN/(TN+FP))
# - f1_neg (F1 score for labelling of negative cases, i.e., 'civil' category; 2*((prec_neg*rec_neg)/(prec_neg+rec_neg))
# - prec_pos (Precision of positive case, i.e., precision of those labelled 'uncivil'; TP/(TP+FP))
# - rec_pos (Recall of positive case, i.e., recall of ground-truth 'uncivil'; TP/(TP+FN))
# - f1_pos (F1 score for labelling of positive cases, i.e., 'uncivil' category; 2*((prec_pos*rec_pos)/(prec_pos+rec_pos))
# - which = ["Pure comment", "Joint sentence-comment"]

df

summary = (
    df.groupby(["Model", "Epoch", "which"])["accuracy"]
      .agg(["mean", "std", "count"])
      .reset_index()
)

summary["se"] = summary["std"] / np.sqrt(summary["count"])

z = 1.96
summary["ci_low"]  = summary["mean"] - z * summary["se"]
summary["ci_high"] = summary["mean"] + z * summary["se"]

summary

# Figure 1
bert = summary[summary["Model"] == "BERT"]
plt.figure(figsize=(10, 6))

for model, g in bert.groupby(["which"]):
    g = g.sort_values("Epoch")

    plt.plot(g["Epoch"], g["mean"], label=model)

    plt.fill_between(
        g["Epoch"],
        g["ci_low"],
        g["ci_high"],
        alpha=0.2
    )

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("BERT: Accuracy over 30 Epochs (95% CI)")
plt.legend(title="Method")
plt.tight_layout()
plt.ylim(0.69,0.9)
images_dir = '/content/drive/MyDrive'
plt.savefig(f"{images_dir}/BERT.png")
plt.show()

# Figure 2
roberta = summary[summary["Model"] == "RoBERTa"]
plt.figure(figsize=(10, 6))

for model, g in roberta.groupby(["which"]):
    g = g.sort_values("Epoch")

    # mean line
    plt.plot(g["Epoch"], g["mean"], label=model)

    # CI ribbon
    plt.fill_between(
        g["Epoch"],
        g["ci_low"],
        g["ci_high"],
        alpha=0.2
    )

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("RoBERTa: Accuracy over 30 Epochs (95% CI)")
plt.legend(title="Method")
plt.tight_layout()
plt.ylim(0.69,0.9)
plt.savefig(f"{images_dir}/RoBERTa.png")
plt.show()

bertweet = summary[summary["Model"] == "BERTweet"]
plt.figure(figsize=(10, 6))

for model, g in bertweet.groupby(["which"]):
    g = g.sort_values("Epoch")

    plt.plot(g["Epoch"], g["mean"], label=model)

    plt.fill_between(
        g["Epoch"],
        g["ci_low"],
        g["ci_high"],
        alpha=0.2
    )

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("BERTweet: Accuracy over 30 Epochs (95% CI)")
plt.legend(title="Method")
plt.tight_layout()
plt.ylim(0.69,0.9)
plt.savefig(f"{images_dir}/BERTweet.png")
plt.show()