# -*- coding: utf-8 -*-
"""Plots, Accuracy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13y8Lz0gpvXtl83Fqnx_QKXvKQjH0fpeD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("data/Eval_epoch.csv")
# Dataset a model-method-epoch-seed combination per row with the following variables:
# - Model = ["BERT", "RoBERTa", "BERTweet"]
# - Epoch = 1:30
# - Seed = 42:61
# - prec_neg (Precision of negative case, i.e., precision of those labelled 'civil'; TN/(TN+FN))
# - rec_neg (Recall of negative case, i.e., recall of ground-truth 'civil'; TN/(TN+FP))
# - f1_neg (F1 score for labelling of negative cases, i.e., 'civil' category; 2*((prec_neg*rec_neg)/(prec_neg+rec_neg))
# - prec_pos (Precision of positive case, i.e., precision of those labelled 'uncivil'; TP/(TP+FP))
# - rec_pos (Recall of positive case, i.e., recall of ground-truth 'uncivil'; TP/(TP+FN))
# - f1_pos (F1 score for labelling of positive cases, i.e., 'uncivil' category; 2*((prec_pos*rec_pos)/(prec_pos+rec_pos))
# - which = ["Pure comment", "Joint sentence-comment"]

df

summary = (
    df.groupby(["Model", "Epoch", "which"])["accuracy"]
      .agg(["mean", "std", "count"])
      .reset_index()
)

summary["se"] = summary["std"] / np.sqrt(summary["count"])

z = 1.96
summary["ci_low"]  = summary["mean"] - z * summary["se"]
summary["ci_high"] = summary["mean"] + z * summary["se"]

summary

# Figure 1
bert = summary[summary["Model"] == "BERT"]
plt.figure(figsize=(10, 6))

for model, g in bert.groupby(["which"]):
    g = g.sort_values("Epoch")

    plt.plot(g["Epoch"], g["mean"], label=model)

    plt.fill_between(
        g["Epoch"],
        g["ci_low"],
        g["ci_high"],
        alpha=0.2
    )

plt.xlabel("Epoch", fontsize=16)
plt.ylabel("Accuracy", fontsize=16)
plt.title("BERT: Accuracy over 30 Epochs (95% CI)", fontsize=20)
plt.legend(title="Method", fontsize=16, title_fontsize=18, loc="lower left")
plt.tight_layout()
plt.ylim(0.69,0.9)

# annotate: Pure comment => 0.8537, epoch 28
# annotate: Pure comment => 0.8427, epoch 30

pure = bert[bert["which"] == "Pure comment"].sort_values("Epoch")

E = 28
y28 = pure.loc[pure["Epoch"].eq(E), "mean"].iloc[0]  

plt.annotate(
    f"E={E}, A={y28:.4f}",
    xy=(E, y28),        
    xycoords="data",
    xytext=(42, -40),          
    textcoords="offset points",
    arrowprops=dict(arrowstyle="->", lw=2),
    ha="right",
    va="bottom",
    fontsize=16
)

joint = bert[bert["which"] == "Joint sentence-comment"].sort_values("Epoch")

E = 21
y21 = joint.loc[joint["Epoch"].eq(E), "mean"].iloc[0] 

plt.annotate(
    f"E={E}, A={y21:.4f}",
    xy=(E, y21),        
    xycoords="data",
    xytext=(66, 25),           
    textcoords="offset points",
    arrowprops=dict(arrowstyle="->", lw=2),
    ha="right",
    va="bottom",
    fontsize=16
)
plt.savefig("BERT.png")
plt.show()

# Figure 2
roberta = summary[summary["Model"] == "RoBERTa"]
plt.figure(figsize=(10, 6))

for model, g in roberta.groupby(["which"]):
    g = g.sort_values("Epoch")

    plt.plot(g["Epoch"], g["mean"], label=model)

    plt.fill_between(
        g["Epoch"],
        g["ci_low"],
        g["ci_high"],
        alpha=0.2
    )

plt.xlabel("Epoch", fontsize=16)
plt.ylabel("Accuracy", fontsize=16)
plt.title("RoBERTa: Accuracy over 30 Epochs (95% CI)", fontsize=18)
plt.legend(title="Method", fontsize=16, title_fontsize=18, loc="lower left")
plt.tight_layout()
plt.ylim(0.69,0.9)
# annotate: Pure => 0.8678, epoch 27
# annotate: Joint => 0.8763, epoch 21
pure = roberta[roberta["which"] == "Pure comment"].sort_values("Epoch")

E = 27
y27 = pure.loc[pure["Epoch"].eq(E), "mean"].iloc[0] 

plt.annotate(
    f"E={E}, A={y27:.4f}",
    xy=(E, y27),           
    xycoords="data",
    xytext=(67, -40),         
    textcoords="offset points",
    arrowprops=dict(arrowstyle="->", lw=2),
    ha="right",
    va="bottom",
    fontsize=16
)

joint = roberta[roberta["which"] == "Joint sentence-comment"].sort_values("Epoch")

E = 21
y21 = joint.loc[joint["Epoch"].eq(E), "mean"].iloc[0]

plt.annotate(
    f"E={E}, A={y21:.4f}",
    xy=(E, y21),           
    xycoords="data",
    xytext=(42, 17),            
    textcoords="offset points",
    arrowprops=dict(arrowstyle="->", lw=2),
    ha="right",
    va="bottom",
    fontsize=16
)


plt.savefig("RoBERTa.png")
plt.show()

# Figure 3
bertweet = summary[summary["Model"] == "BERTweet"]
plt.figure(figsize=(10, 6))

for model, g in bertweet.groupby(["which"]):
    g = g.sort_values("Epoch")

    plt.plot(g["Epoch"], g["mean"], label=model)

    plt.fill_between(
        g["Epoch"],
        g["ci_low"],
        g["ci_high"],
        alpha=0.2
    )

plt.xlabel("Epoch", fontsize=16)
plt.ylabel("Accuracy", fontsize=16)
plt.title("BERTweet: Accuracy over 30 Epochs (95% CI)", fontsize=18)
plt.legend(title="Method", fontsize=16, title_fontsize=18, loc="lower left")
plt.tight_layout()
plt.ylim(0.69,0.9)

# annotate: Pure => 0.8729, epoch 30
# annotate: Joint => 0.8810, epoch 29

pure = bertweet[bertweet["which"] == "Pure comment"].sort_values("Epoch")

E = 30
y30 = pure.loc[pure["Epoch"].eq(E), "mean"].iloc[0] 

plt.annotate(
    f"E={E}, A={y30:.4f}",
    xy=(E, y30),            
    xycoords="data",
    xytext=(0, -30),           
    textcoords="offset points",
    arrowprops=dict(arrowstyle="->", lw=2),
    ha="right",
    va="bottom",
    fontsize=16
)

joint = bertweet[bertweet["which"] == "Joint sentence-comment"].sort_values("Epoch")

E = 29
y29 = joint.loc[joint["Epoch"].eq(E), "mean"].iloc[0]  

plt.annotate(
    f"E={E}, A={y29:.4f}",
    xy=(E, y29),          
    xycoords="data",
    xytext=(22, 10),            
    textcoords="offset points",
    arrowprops=dict(arrowstyle="->", lw=2),
    ha="right",
    va="bottom",
    fontsize=16
)

plt.savefig("BERTweet.png")
plt.show()
